services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: directory_sql
    environment:
      SA_PASSWORD: "SecurePassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cuidarmed_net
    volumes:
      - sql_data:/var/opt/mssql

  directoryms:
    build:
      context: .
      dockerfile: DirectoryMS/Dockerfile
    container_name: directoryms_api
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=DirectoryMS;User Id=sa;Password=SecurePassword123!;Encrypt=True;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    depends_on:
      - sql
    networks:
      - cuidarmed_net

volumes:
  sql_data: {}

networks:
  cuidarmed_net:
    external: true
