services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      MSSQL_SA_PASSWORD: "SecurePassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_ENCRYPT: "false"
    ports:
      - "1433:1433"
    networks:
      - cuidarmed_net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'SecurePassword123!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  directoryms:
    build:
      context: .
      dockerfile: DirectoryMS/Dockerfile
    container_name: directoryms_api
    depends_on:
      sql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql,1433;Database=DirectoryMS;User Id=sa;Password=SecurePassword123!;Encrypt=False;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    networks:
      - cuidarmed_net

networks:
  cuidarmed_net:
    external: true
